#!/usr/bin/env bash

set -e

# run tests with -s to display printouts and --log-cli-level to get logger output
pytest --cov=./custom_components/broodminder --cov-branch --log-cli-level=INFO -s

# generate coverage report in html and xml
coverage html
coverage xml
